# Generated by Django 6.0 on 2026-01-08 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('descrizione', models.TextField()),
                ('data_uscita', models.DateField()),
                ('durata_minuti', models.PositiveIntegerField()),
                ('genere', models.CharField(max_length=100)),
                ('regista', models.CharField(max_length=100)),
                ('cast_principale', models.TextField()),
                ('locandina_url', models.URLField()),
                ('trailer_url', models.URLField(blank=True, null=True)),
                ('rassegna', models.BooleanField(default=False)),
                ('uscita_locale', models.DateField(blank=True, null=True)),
                ('in_programmazione', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Film',
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Sale',
            },
        ),
        migrations.CreateModel(
            name='Recensione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autore', models.CharField(max_length=100)),
                ('contenuto', models.TextField()),
                ('valutazione', models.IntegerField()),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.film')),
            ],
            options={
                'verbose_name_plural': 'Recensioni',
            },
        ),
        migrations.CreateModel(
            name='Proiezione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ora', models.DateTimeField()),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema.film')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema.sala')),
            ],
            options={
                'verbose_name_plural': 'Proiezioni',
                'constraints': [models.UniqueConstraint(fields=('sala', 'data_ora'), name='uniq_proiezione_sala_orario')],
            },
        ),
        migrations.CreateModel(
            name='Posto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_posto', models.CharField(max_length=10)),
                ('fila', models.CharField(max_length=5)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.sala')),
            ],
            options={
                'verbose_name_plural': 'Posti',
                'constraints': [models.UniqueConstraint(fields=('sala', 'fila', 'numero_posto'), name='uniq_posto_per_sala')],
            },
        ),
    ]
