# Generated by Django 6.0.1 on 2026-01-12 20:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_alter_recensione_autore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recensione',
            options={'ordering': ['-create_at', '-id'], 'verbose_name_plural': 'Recensioni'},
        ),
        migrations.AddField(
            model_name='recensione',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
