# Generated by Django 6.0.1 on 2026-01-13 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_socio_newslettersubscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslettersubscription',
            name='consent_at',
        ),
        migrations.RemoveField(
            model_name='newslettersubscription',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='newslettersubscription',
            name='source',
        ),
        migrations.RemoveField(
            model_name='newslettersubscription',
            name='user',
        ),
    ]
