# Generated by Django 6.0 on 2026-01-08 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinema', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Biglietto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prezzo', models.DecimalField(decimal_places=2, default=8.0, max_digits=4)),
                ('nome_cliente', models.CharField(blank=True, max_length=120)),
                ('telefono_cliente', models.CharField(blank=True, max_length=30)),
                ('stato', models.CharField(choices=[('PRE', 'Prenotato'), ('PAG', 'Pagato'), ('ANN', 'Annullato')], default='PRE', max_length=3)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('posto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema.posto')),
                ('proiezione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biglietti', to='cinema.proiezione')),
                ('utente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('proiezione', 'posto'), name='uniq_posto_per_proiezione')],
            },
        ),
    ]
